## Практическая работа

В этой практической работе пять обязательных задач.

*Обязательные задачи* помогут проверить, что вы действительно усвоили материал модуля. Сдайте их на проверку.

Удачи!

Цели практической работы: 


1.   Потренироваться в обучении модели линейной регрессии.
2.   Потренироваться в обучении модели логистической регрессии. 
3.   Потренироваться в обучении модели многослойного персептрона.





Что оценивается:

*   Все пункты и критерии приёмки по каждому заданию выполнены.
*   Код оформлен и работает корректно.





Как отправить работу на проверку:

Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему куратору.

В этом задании вам нужно построить модель классификации, определяющую категорию цены/цену подержанного автомобиля в зависимости от характеристик транспортного средства. 

Мы будем использовать датасет из коллекции подержанных автомобилей, выставленных на продажу в Соединенных Штатах. Он уже подготовлен, без выбросов и с категориальными фичами, преобразованными с помощью one hot encoding, и количественными фичами, стандартизированными с помощью скейлеров.


### Описание датасета:
- `id`: идентификатор записи;
- `is_manufacturer_name`: признак производителя автомобиля;

- `region_*`: регион;
- `x0_*`: тип топлива;
- `manufacturer_*`: производитель;
- `short_model_*`: сокращённая модель автомобиля;
- `title_status_*`: статус;
- `transmission_*`: коробка передач;
- `state_*`: штат;
- `age_category_*`: возрастная категория автомобиля;

- `std_scaled_odometer`: количество пройденных миль (после стандартизации);
- `year_std`: год выпуска (после стандартизации);
- `lat_std`: широта (после стандартизации);
- `long_std`: долгота (после стандартизации);
- `odometer/price_std`: отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`: количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`: количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`: длина наименования автомобиля (после стандартизации);
- `model_word_count_std`: количество слов в наименовании автомобиля (после стандартизации);
- `month_std`: номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`: день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`: количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`: стоимость;
- `price_category`: категория цены.

## Обязательные задачи

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error
from sklearn.model_selection import train_test_split 
from sklearn.neural_network import MLPClassifier

In [2]:
df = pd.read_csv('vehicles_dataset_prepared.csv')
df.head()

id  price price_category  is_audi  is_ford  is_chevrolet  \
0  7308295377  54990           high        0        0             0   
1  7316380095  16942         medium        0        1             0   
2  7313733749  35590           high        0        0             0   
3  7308210929  14500         medium        0        0             0   
4  7303797340  14590         medium        0        0             0   

   is_toyota  x0_diesel  x0_electric  x0_gas  ...  long_std  year_std  \
0          0        1.0          0.0     0.0  ...  0.484245  1.322394   
1          0        0.0          0.0     0.0  ...  1.110800  0.695973   
2          0        0.0          0.0     1.0  ...  0.531185  0.852578   
3          1        0.0          0.0     1.0  ...  0.853562  0.226157   
4          0        0.0          0.0     0.0  ...  0.557607  0.069552   

   odometer/price_std  desc_len_std  model_in_desc_std  model_len_std  \
0           -0.510784      0.632075          -0.155788       1.163032   
1           -0.402947     -0.646781          -0.155788       0.932087   
2           -0.514480      0.560744          -0.155788       0.470197   
3           -0.241883      0.180435          -0.155788      -0.915473   
4           -0.333074      0.766366          -0.155788       1.163032   

   model_word_count_std  month_std  dayofweek_std  diff_years_std  
0              1.910669  -0.615846       1.120284       -1.322394  
1              1.235799   1.623784      -1.374972       -0.695973  
2              0.560930  -0.615846      -0.376870       -0.852578  
3             -0.788810  -0.615846       1.120284       -0.226157  
4              1.910669  -0.615846       0.122182       -0.069552  

[5 rows x 1463 columns]

**Задача 0. Линейная регрессия**

Вспомните задачу по предсказанию стоимости поддержанного автомобиля. Попробуем обучить модель линейной регрессии для предсказания цены автомобиля (колонка `price`). Для этого проделайте следующие шаги:

- Подготовьте данные: удалите колонки, которые косвенно содержат информацию о целевой переменной (`odometer/price_std`, `price_category`).
- Разделите выборку на треин и тест в отношении 70/30.
- Обучите модель линейной регрессии с дефолтными параметрами.
- Посчитайте значение метрики mae на тестовой выборке для линейной регрессии.
- Выведите получившиеся коэффициенты линейной регрессии при каждом параметре обучающей выборки с помощью метода `coef_`. Есть ли коэффициенты, которые равны нулю? Если есть, выведите названия фичей с нулевым коэффициентом
- Удалите фичи, коэффициенты которых равны нулю. И переобучите модель. Убедитесь, что значение метрики не изменилось.



In [15]:
df_train = df.drop(columns=['odometer/price_std', 'price_category'])
x = df_train.drop(columns=['price'])
y = df_train['price']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
print(f'MAE: {mae}')

MAE: 4600.341121893259


In [16]:
coefs = pd.DataFrame(model.coef_, x.columns, columns=['coef'])
coefs[coefs.coef == 0]

coef
manufacturer_ferrari   0.0

In [17]:
x = df_train.drop(['price', "manufacturer_ferrari"], axis=1)
y = df_train['price']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
print(f'MAE: {mae}')

MAE: 4600.341117382269


ну оно изменилось, но крайне незначительно

**Задача 1. Логистическая регрессия**

Теперь в рамках тех же данных попробуйте предсказать `price_category` с помощью алгоритма логистической регрессии. Предварительно из датафрейма удалите переменные, в которых косвенно содержится информация о целевой переменной (`odometer/price_std`, `price`). 

Для обученной модели нужно:

- рассчитать и вывести метрику качества (accuracy) на тренировочной выборке;
- сделать предикт на тестовых данных и положить его в переменную `logreg_pred`;
- рассчитать и вывести accuracy и confusion_matrix на тестовой выборке.


Задание засчитывается, если: 
- accuracy на тренировочной выборке > 87%;
- accuracy на тестовой выборке > 75.5%.

Для улучшения метрики можно преобразовывать входные данные, тюнить параметры логистической регрессии.

In [3]:
# Ваш код подготовки данных здесь. Допишите инициализацию входных фичей и целевую переменную
x = df.drop(["odometer/price_std", "price", "price_category", "id"], axis=1)
y = df['price_category']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [7]:
logreg = LogisticRegression(C=2.2, max_iter=1000)#solver="newton-cg"  

logreg.fit(x_train, y_train)

log_pred = logreg.predict(x_test)
accuracy_score(y_train, logreg.predict(x_train)), accuracy_score(y_test, log_pred), confusion_matrix(y_test, log_pred)

(0.8730135155205703,
 0.7595287595287595,
 array([[801,  23, 173],
        [ 23, 771, 159],
        [151, 165, 620]], dtype=int64))

**Задача 2. Многослойный персептрон**

Решите задачу, поставленную в предыдущем задании, применив модель многослойного персептрона. Добейтесь лучших значений точности на тренировочной и тестовой выборках, чем на логистической регрессии, с помощью данного алгоритма. 

Значимым увеличением точности в данном задании будем считать увеличение больше, чем на 0.01 по метрике accuracy.

In [20]:
x = df.drop(["odometer/price_std", "price", "price_category", "id"], axis=1)
y = df['price_category']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

mlp = MLPClassifier(hidden_layer_sizes=(200, 100, 50))
mlp.fit(x_train, y_train)

accuracy_score(y_train, mlp.predict(x_train)), accuracy_score(y_test, mlp.predict(x_test)), confusion_matrix(y_test, mlp.predict(x_test))

(0.9919798009802465,
 0.7654192654192654,
 array([[872,  14, 111],
        [ 27, 713, 213],
        [190, 122, 624]], dtype=int64))

**Задача 3. Сравнение с древовидными моделями**

Обучите модель случайного леса на тех же данных для предсказания `price_category`. Сравните качество с моделью логистической регрессии и многослойного персептрона. Словами опишите, какая из моделей в каких случаях работает лучше по результатам на тестовой выборке, и обоснуйте свой выбор.

In [8]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=1000, random_state=42)
rf.fit(x_train, y_train)

rf_pred = rf.predict(x_test)
accuracy_score(y_train, rf.predict(x_train)), accuracy_score(y_test, rf_pred), confusion_matrix(y_test, rf_pred)

(1.0,
 0.7616077616077616,
 array([[804,  38, 155],
        [ 14, 808, 131],
        [145, 205, 586]], dtype=int64))

Различие вообще говоря минимальное, однако предпочтение я бы отдал перцептрону, поскольку у него лучшая точность и работа не занимает слишком много времени

**Задача 4. Стратегия голосования**

Реализуйте стратегию голосования для предсказания целевой переменной.
Голосование в задаче классификации — это когда несколько моделей выдают свои предикты, и финальным выбирается тот предикт, который предсказали большинство моделей.

Для реализации этой стратегии проделайте следующее:

- сохраните предсказания каждой из моделей (случайный лес, многослойный персептрон, логистическая регрессия) для тестовой выборки в датафрейм `pred_df`;
- в четвертую колонку `target` положите тот класс, который предсказало большинство классификаторов. Например, если в строке были значения `high, medium, medium`, в `target` нужно положить `medium`.

     Если в строке три разных класса — `high, medium, low`, — придумайте свою стратегию по выбору значения. Самая простая стратегия: выбрать рандомно одно значение из трёх.

- посчитайте точность предсказания с помощью голосования. Выведите значения метрик accuracy и confusion_matrix.


Добейтесь значения точности > 78% 

In [9]:
logreg = LogisticRegression(C=2.2, max_iter=1000)
mlp = MLPClassifier(hidden_layer_sizes=(200, 100, 50), max_iter=1000, activation="logistic")
rf = RandomForestClassifier(n_estimators=200)

logreg.fit(x_train, y_train)
mlp.fit(x_train, y_train)
rf.fit(x_train, y_train)

logreg_pred = logreg.predict(x_test)
mlp_pred = mlp.predict(x_test)
rf_pred = rf.predict(x_test)

pred_df = pd.DataFrame({
    'logreg': logreg_pred,
    'mlp': mlp_pred,
    'rf': rf_pred
})


def vote(row):
    vote_counts = row.value_counts()
    
    if len(vote_counts) == 1:
        return vote_counts.index[0]
    
    elif len(vote_counts) == 2:
        return vote_counts.idxmax()
    
    else:
        return np.random.choice(vote_counts.index)

pred_df['target'] = pred_df.apply(vote, axis=1)

accuracy_score(y_test, pred_df['target']), confusion_matrix(y_test, pred_df['target'])

(0.7803187803187803,
 array([[807,  21, 169],
        [ 15, 803, 135],
        [127, 167, 642]], dtype=int64))

**Примечание:**

В этом домашнем задании в задаче номер 1 и далее перед вами встал выбор: включать ли в обучение колонку `id`. При удалении данной колонки во время обучении логистической регрессии качество заметно улучшается.

Вообще обучать любую модель (будь то логистическая или линейная регрессия, или древовидный алгоритм) на данных айдишников не считается хорошей практикой. Как правило, между `id` и целевой переменной не должно быть никаких взаимосвязей. Включая колонку `id` в качества атрибута в обучение, вы стараетесь "заточить" результаты своей модели под айдишники записей. Таким образом модель обучится на некотором наборе "частных случаев", и, возможно, не обратит внимание на общие зависимости.   